name: CICD

on:
  push:
    branches: [test]

jobs:
  code-clone:
    runs-on: ubuntu-latest
    steps:
      - name: code clone
        uses: actions/checkout@v4
        with:
          ref: 'test'
  build:
    runs-on: ubuntu-latest
    steps:
      - name: path and directory
        run: pwd && ls -lrth 
        
      - name: docker build
        run: docker build -f Dockerfile -t online-app:latest .
