name: CICD

on:
  push:
    branches: [test]

jobs:
  code-clone:
    runs-on: ubuntu-latest
    steps:
      - name: code clone
        uses: actions/checkout@v4
        with:
          ref: 'test'
      - name: docker build
        run: docker build -f Dockerfile -t online-app:latest .
      - name: docker run
        run: docker run -d -p 80:80 online-app:latest
 
        
      
